package com.kenyahmis.dmiapi.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.kenyahmis.dmiapi.validator.ValidCaseStatus;
import com.kenyahmis.dmiapi.validator.ValidTimestamp;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import lombok.Data;
import java.util.ArrayList;
import java.util.List;

@Data
public class CaseDto {

    @Schema(description = "unique id for the submitted case. The value should be generated by the submitting EMR and should be unique for each case")
    @NotBlank
    private String caseUniqueId;
    @NotBlank
    private String hospitalIdNumber;
    @ValidCaseStatus
    private String status;
    private String finalOutcome;
    @ValidTimestamp
    private String finalOutcomeDate;
    @ValidTimestamp
    private String interviewDate;
    @ValidTimestamp
    private String admissionDate;
    @ValidTimestamp
    private String outpatientDate;
    @ValidTimestamp
    private String createdAt;
    @ValidTimestamp
    private String updatedAt;
    @Valid
    private SubjectDto subject;
    @Valid
    private List<VitalSignsDto> vitalSigns;
    @Valid
    @JsonProperty("riskFactors")
    private List<RiskFactorDto> riskFactorDtoList = new ArrayList<>();
    @Valid
    @JsonProperty("vaccinations")
    private List<VaccinationDto> vaccinationDtoList = new ArrayList<>();
    @Valid
    private List<DiagnosisDto> diagnosis = new ArrayList<>();
    @JsonProperty("complaints")
    @Valid
    private List<ComplaintDto> complaintDtoList = new ArrayList<>();
    @JsonProperty("lab")
    @Valid
    private List<LabDto> labDtoList = new ArrayList<>();
}
