version: '3.5'
services:
  dmi-api-slim:
    build: ../
    image: khmis/dmi-api:latest-${LABEL}
    container_name: dmi-api-${LABEL}
    ports:
      - "${DMI_API_PORT:-8088}:8088"
    depends_on:
      - kafka-01-slim
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KEYCLOAK_ISSUER_URL: ${KEYCLOAK_ISSUER_URL}
      KEYCLOAK_JWT_CERT_URL: ${KEYCLOAK_JWT_CERT_URL}
      KEYCLOAK_TOKEN_URL: ${KEYCLOAK_TOKEN_URL}
      SPRING_DOC_SERVER_URL: ${SPRING_DOC_SERVER_URL}
  kafka-01-slim:
    image: bitnami/kafka:3.4.1
    container_name: dmi-kafka-01-${LABEL}
    user: root
    restart: unless-stopped
    environment:
      BITNAMI_DEBUG: 'true'
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: 'broker,controller'
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-01-slim:9092,EXTERNAL://kafka-01-slim:9094
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka-01-slim:9093
      ALLOW_PLAINTEXT_LISTENER: 'yes'
